version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 8
  complex-logic:
    enabled: true
    config:
      threshold: 30
  file-lines:
    enabled: true
    config:
      threshold: 1000
  method-complexity:
    enabled: true
    config:
      threshold: 30
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 100
  nested-control-flow:
    enabled: true
    config:
      threshold: 8
  return-statements:
    enabled: false
    #config:
    #  threshold: 4
  similar-code:
    enabled: false
    #config:
    #  threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: false
    #config:
    #  threshold: #language-specific defaults. overrides affect all languages.

plugins:
  gofmt:
    enabled: true
  golint:
    enabled: true
    config:
      min_confidence: 0.9
  govet:
    enabled: true

#exclude_patterns:
