version: 2
jobs:
  build:
    docker:
      - image: sudachen/go-mxnet-ci

    parallelism: 1

    environment:
      #OMP_NUM_THREADS: 4
      #MXNET_CPU_WORKER_NTHREADS: 2
      CC_TEST_REPORTER_ID: 3497043e6266d8dd8e96f0a37963851e268c88881e8886b3930f57435e851a75

    steps:
      - checkout

      - restore_cache:
          # https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache

      - run: make build

      - run: make run-tests

      - run: mkdir -p github.com/sudachen &&
             ln -s $(pwd) github.com/sudachen/go-dnn &&
             /usr/local/bin/cc-test-reporter after-build

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

workflows:
  version: 2
  build-workflow:
    jobs:
      - build